#!/bin/bash
#
# # The first input parameter indicates the KB_KEY, allowing for
# multiple KaBOB builds in the same Docker environment.
#
# The second input parameter is the version of the kabob container that
# should be called to generate the RDF.
#
# The third input parameter should be an integer (1-5) indicating the
# number of docker containers to use to generate ICE RDF for NCBI
# taxonomy code 9606 (human).
#
#
# This script inspired by:
# http://kimh.github.io/blog/en/docker/using-docker-to-run-cucumber-tests-in-parallel/
#

KB_KEY=$1
TAX="-t 9606"
MAVEN="/usr/bin/mvn"

KABOB_CONTAINER_VERSION=$2

case $3 in
    1) DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ,UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML,UNIPROT_IDMAPPING")
       ;;
    2) DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML,UNIPROT_IDMAPPING")
       ;;
    3) DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML" "UNIPROT_IDMAPPING")
       ;;
    4) DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY" "REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML" "UNIPROT_IDMAPPING")
       ;;
    5) DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES" "IREFWEB_HUMAN_ONLY" "REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML" "UNIPROT_IDMAPPING")
       ;;
    *) echo "Expected a number between 1-5 for the number of Docker containers to spin up to generate RDF. Observed $3 instead. By default, only a single container will be used for generating RDF."
       DATASOURCES=("RNACENTRAL_ID_MAPPING,BIOMART_GENE_IDENTIFIER_MAPPING,BIOMART_TRANSCRIPT_IDENTIFIER_MAPPING,BIOMART_PROTEIN_IDENTIFIER_MAPPING,BIOMART_CENTRAL_DOGMA_IDENTIFIER_LINKING,CURATED_TF,BIOGRID_PROTEIN_INTERACTIONS,BIOGRID_MULTIVALIDATED_PHYSICAL_PROTEIN_INTERACTIONS,BIOGRID_PROTEIN_CHEMICAL_INTERACTIONS,BIOPLEX,PR_MAPPINGFILE,PHARMGKB_DRUG,PHARMGKB_DISEASE,PHARMGKB_GENE,PHARMGKB_RELATION,NCBIGENE_MIM2GENE,UNIPROT_TREMBL_SPARSE_HUMAN_ONLY,MIRBASE,DRUGBANK,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ,UNIPROT_SWISSPROT,INTERPRO_PROTEIN2IPR,INTERPRO_XML,UNIPROT_IDMAPPING")
       ;;
esac


DID=""
COUNTER=1
for ds in "${DATASOURCES[@]}"
do
    echo "Starting kabob container to process: $ds"
    DID=$DID" "`docker run -d --name "rdf_gen_$COUNTER" --volumes-from kabob_data-${KB_KEY} ucdenverccp/kabob:${KABOB_CONTAINER_VERSION} ./ice-rdf-gen.sh "$TAX" "$ds" "$MAVEN" "$COUNTER"`
    COUNTER=$((COUNTER + 1))
done
docker wait $DID
docker rm $DID

echo "Checking logs for failed RDF generation processes. If any errors are listed below, steps must be taken to re-process those data sources that failed."
docker run --rm --name "rdf_gen_check" --volumes-from kabob_data-${KB_KEY} ucdenverccp/kabob:${KABOB_CONTAINER_VERSION} sh -c "grep 'RDF GEN ERROR' /kabob_data/logs/*.log*"
echo "Check complete."